Wells Operatic Society/Models/PreviousProductionsViewModel.cs
using System.Collections.Generic;
using WellsOperaticSociety.Models.UmbracoModels;

namespace WellsOperaticSociety.Web.Models
{
    public class PreviousProductionsViewModel
    {
        public List<Function> Functions { get; set; }
        public int PageSize { get; set; }
        public int Row { get; set; }
        public int TotalItemCount { get; set; }
    }
}

Wells Operatic Society/Controllers/AdminSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using DataTables.AspNet.Core;
using DataTables.AspNet.Mvc5;
using log4net;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Stripe;
using umbraco.cms.businesslogic.packager;
using Umbraco.Web.Mvc;
using WellsOperaticSociety.BusinessLogic;
using WellsOperaticSociety.EmailService;
using WellsOperaticSociety.Models;
using WellsOperaticSociety.Models.AdminModels;
using WellsOperaticSociety.Models.EmailModels;
using WellsOperaticSociety.Models.Enums;
using WellsOperaticSociety.Models.MemberModels;
using WellsOperaticSociety.Models.ReportModels;
using WellsOperaticSociety.Web.Helper;
using WellsOperaticSociety.Web.Models;
using Member = WellsOperaticSociety.Models.MemberModels.Member;
using SortDirection = DataTables.AspNet.Core.SortDirection;
using WellsOperaticSociety.Models.StandardModels;

namespace WellsOperaticSociety.Web.Controllers
{
    public class AdminSurfaceController : SurfaceController
    {
        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        public AdminSurfaceController()
        {
            this.ActionInvoker = new RenderActionInvokerAsync();
        }

        public ActionResult ManageMembers(int? pageSize, int? row)
        {
            var model = new ManageMembershipViewModel
            {
                Members = Services.MemberService.GetAllMembers().Take(50)
            };

            return PartialView("ManageMembership", model);
        }

        public ActionResult ManageMember(int id)
        {

            DataManager dm = new DataManager();
            var member = Members.GetById(id);
            if (member == null)
            {
                TempData["ErrorMessage"] =
                    "The member you are looking for could not be found. Please try again but if it persists please give your handy IT people a shout :)";
                _log.Error(
                    $"A member with the id of {id} could not be found in the admin surface controller ManageMember function");
                return null;
            }

            var model = new ManageMemberViewModel();
            model.Member = new Member(member);
            model.Memberships = dm.GetMembershipsForUser(id);

            //setup new membership
            var curMemberships = dm.GetMembershipsForUser(id);
            var startDate = DateTime.Now;
            var endDate = DateTime.Now.AddYears(1);
            if (curMemberships != null && curMemberships.Count > 0)
            {
                var previous = curMemberships.OrderByDescending(m => m.EndDate).First();
                startDate = previous.StartDate.AddYears(1);
                endDate = startDate.AddYears(1).AddDays(-1);
            }

            model.NewMembership = new Membership()
            {
                StartDate = startDate,
                EndDate = endDate,
                Member = id,
                IsSubscription = false
            };

            try
            {
                model.IsSubscribedToMailingList =
                    Task.Run(() => dm.IsUserSubscribedToMailChimpList(MailChimpListIds.MailingList, model.Member.Email))
                        .Result;
                model.IsSubscribedToMemberList =
                    Task.Run(() => dm.IsUserSubscribedToMailChimpList(MailChimpListIds.Membership, model.Member.Email))
                        .Result;
            }
            catch (Exception ex)
            {
                _log.Error("Error fetching mailchimp subscription information", ex);
            }

            model.HasMemberRole = System.Web.Security.Roles.IsUserInRole(model.Member.Email, "Member");
            model.HasEditorRole = System.Web.Security.Roles.IsUserInRole(model.Member.Email, "Editor");
            model.HasCommitteeRole = System.Web.Security.Roles.IsUserInRole(model.Member.Email, "Committee Member");
            return PartialView("ManageMember", model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateMember(ManageMemberViewModel model)
        {
            if (ModelState.IsValid)
            {
                //No user id was passed in
                if (model.Member.Id == 0)
                {
                    _log.Error("Trying to update a member on the admin form but no userId was posted back");
                    ModelState.AddModelError("", "We could not find a user with that id to update");
                    return CurrentUmbracoPage();
                }

                var memberService = Services.MemberService;
                var member = memberService.GetById(model.Member.Id);
                //couldnt find member
                if (member == null)
                {
                    _log.Error(
                        $"Trying to update a member on the admin form but the member with id {model.Member.Id} could not be found");
                    ModelState.AddModelError("", "We could not find a user with that id to update");
                    return CurrentUmbracoPage();
                }
                //update email if email is different
                if (model.Member.Email != member.Email)
                {
                    //check if the new email already exists in the system
                    if (memberService.GetByEmail(model.Member.Email) != null)
                    {
                        ModelState.AddModelError("Email",
                            "This email address already exists in the system and emails must be unique.");
                        return CurrentUmbracoPage();
                    }
                }

                try
                {
                    DataManager dm = new DataManager();
                    dm.AddOrUpdateMember(model.Member, true);
                    //mailing list subscribe
                    if (model.IsSubscribedToMailingList)
                        Task.Run(
                            () =>
                                dm.AddOrUpdateUserToMailChimpList(MailChimpListIds.MailingList, model.Member.Email,
                                    model.Member.FirstName, model.Member.LastName));
                    else
                    {
                        var mailingListMember =
                            Task.Run(
                                () =>
                                    dm.IsUserSubscribedToMailChimpList(MailChimpListIds.MailingList, model.Member.Email))
                                .Result;
                        if (mailingListMember)
                        {
                            Task.Run(
                                () =>
                                    dm.AddOrUpdateUserToMailChimpList(MailChimpListIds.MailingList, model.Member.Email,
                                        model.Member.FirstName, model.Member.LastName, true));
                        }
                    }

                    //members mailing list subscribe
                    if (model.IsSubscribedToMailingList)
                        Task.Run(
                            () =>
                                dm.AddOrUpdateUserToMailChimpList(MailChimpListIds.Membership, model.Member.Email,
                                    model.Member.FirstName, model.Member.LastName));
                    else
                    {
                        var memberListMember =
                            Task.Run(
                                () =>
                                    dm.IsUserSubscribedToMailChimpList(MailChimpListIds.Membership, model.Member.Email))
                                .Result;
                        if (memberListMember)
                        {
                            Task.Run(
                                () =>
                                    dm.AddOrUpdateUserToMailChimpList(MailChimpListIds.Membership, model.Member.Email,
                                        model.Member.FirstName, model.Member.LastName, true));
                        }
                    }

                    //Security
                    if (model.HasMemberRole)
                    {
                        dm.AddUserToRole(model.Member.Id, "Member");
                    }
                    else
                    {
                        dm.RemoveUserFromRole(model.Member.Id, "Member");
                    }
                    if (model.HasEditorRole)
                    {
                        dm.AddUserToRole(model.Member.Id, "Editor");
                    }
                    else
                    {
                        dm.RemoveUserFromRole(model.Member.Id, "Editor");
                    }
                    if (model.HasCommitteeRole)
                    {
                        dm.AddUserToRole(model.Member.Id, "Committee Member");
                    }
                    else
                    {
                        dm.RemoveUserFromRole(model.Member.Id, "Committee Member");
                    }
                }
                catch (Exception ex)
                {
                    _log.Error("There was an error updating a profile with the exception as follows", ex);
                    ModelState.AddModelError("",
                        "There was an error updating this profile. Give us a shout if this keeps happening and we will find out whats going on");
                    return CurrentUmbracoPage();
                }
                TempData["SuccessMessage"] =
                    $"Hurray!! Everything worked and you have update the profile for {model.Member.FirstName} {model.Member.LastName}";
                return RedirectToCurrentUmbracoPage("?id=" + model.Member.Id);
            }
            return CurrentUmbracoPage();
        }

        public PartialViewResult MemberSearch(string search)
        {

Wells Operatic Society/Controllers/MainSurfaceController.cs
using System.Reflection;
using System.Web.Mvc;
using log4net;
using Umbraco.Web.Mvc;
using WellsOperaticSociety.BusinessLogic;
using WellsOperaticSociety.Models;
using WellsOperaticSociety.Models.EmailModels;
using WellsOperaticSociety.Web.Models;

namespace WellsOperaticSociety.Web.Controllers
{
    public class MainSurfaceController : SurfaceController
    {

        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        public ActionResult FunctionCards(int quantity = 3)
        {
            DataManager manager = new DataManager();

            var model = manager.GetUpcomingFunctions(quantity, 0);

            return PartialView("FunctionCards", model);

        }

        public ActionResult WhatsOn(int quantity = 10)
        {
            DataManager manager = new DataManager();

            var model = manager.GetUpcomingFunctions(quantity, 0);

            return PartialView("WhatsOn", model);
        }

        public ActionResult PreviousProductions(int? pageSize, int? row)
        {
            pageSize = pageSize ?? 10;
            row = row ?? 0;

            DataManager manager = new DataManager();

            var model = new PreviousProductionsViewModel()
            {
                Functions = manager.GetExpiredFunctions((int) pageSize, (int) row),
                PageSize = (int) pageSize,
                Row = (int) row,
                TotalItemCount = manager.GetCountOfExpiredFunctions()
            };

            return PartialView("PreviousProductions", model);
        }

        public ActionResult ContactUsForm()
        {
            var model = new ContactUs();

            return PartialView("ContactUsForm", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitContactUsForm(ContactUs model)
        {
            if (ModelState.IsValid)
            {
                string encodedResponse = Request.Form["g-Recaptcha-Response"];
                var response = ReCaptcha.Validate(encodedResponse, SensativeInformation.ReCaptchaKeys.ReCaptchaSecretKey);
                bool isCaptchaValid = response.ToLower() == "true"
                        ? true
                        : false;
                if (!isCaptchaValid)
                {
                    ModelState.AddModelError("", "Please verify you are not a robot");
                    return CurrentUmbracoPage();
                }

                ContactUsEmailModel emailModel = new ContactUsEmailModel();
                emailModel.Info = model;
                emailModel.BaseUri = UrlHelpers.GetBaseUrl();
                ViewData.Model = emailModel;
                var html = RazorHelpers.RenderRazorViewToString("~/Views/Emails/ContactUsEmail.cshtml", ControllerContext, ViewData, TempData);
                var emailService = new EmailService.EmailHelpers();
                emailService.SendEmail("info@wellslittletheatre.com","Query from contact form", html);
                TempData["Success"] = "That is winging its way to us now. We will be in contact as soon as we can.";
                return RedirectToCurrentUmbracoPage();
            }
            return CurrentUmbracoPage();
        }
    }
}

Wells Operatic Society/Views/MacroPartials/AdminManageSeats.cshtml
@Html.Action("ManageSeats","AdminSurface")

Wells Operatic Society/Views/MacroPartials/AdminReports.cshtml
@using WellsOperaticSociety.BusinessLogic
@{
    var dm = new DataManager();
    var membershipReportUrl = dm.GetMembershipReportNode().Url;
}
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Vehicle registration list</h3>
        </div>
        <div class="panel-body">
            <p>Print a list of active member registration numbers. That are pulled from the member record.</p>
            <a href="@Url.Action("VehicleRegistrationReport", "AdminSurface")" class="btn btn-info btn-fill"><i class="fa fa-car"></i> Print</a>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Long service awards</h3>
        </div>
        <div class="panel-body">
            <p>Print a list of all of the upcoming and overdue long service awards. These can be managed in the admin -> manage long service award section</p>
            <a href="@Url.Action("LongServiceReport", "AdminSurface")" class="btn btn-info btn-fill"><i class="pe-7s-medal"></i> Print</a>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Membership reports</h3>
        </div>
        <div class="panel-body">
            <p>Customise a report of our membership</p>
            <a href="@membershipReportUrl" class="btn btn-info btn-fill"><i class="pe-7s-medal"></i> Next</a>
        </div>
    </div>
</div>

Wells Operatic Society/Views/MacroPartials/BoxOfficeInformation.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var dataManager = new WellsOperaticSociety.BusinessLogic.DataManager(Umbraco.UmbracoContext);

    var model = dataManager.GetBoxOfficeFunctionInformation();
    var sortedList = model.OpeningTimes.OrderBy(m => m.Date).ThenBy(m => m.OpeningTime);
    var midpoint = (int)Math.Ceiling((decimal)sortedList.Count() / 2);
    var openingTimesList1 = sortedList.Take(midpoint).ToList();
    var openingTimesList2 = sortedList.Skip(midpoint).ToList();
}
@helper BoxofficeTimeRow(WellsOperaticSociety.Models.StandardModels.BoxOfficeTime entry)
    {
        var message = entry.Message.IsNotNullOrEmpty() ? "<span class=\"message\">" + entry.Message + "</span>" : string.Empty;

        <div class="date-entry">
            <div class="day-wrapper"><span class="day">@entry.Date.ToString("ddd")</span><span class="date">@entry.Date.Day</span></div>
            <div class="month-year-time-wrapper"><span class="date">@entry.Date.Date.ToString("MMM")</span><span class="time">@entry.OpeningTime.ToString(@"hh\:mm") - @entry.ClosingTime.ToString(@"hh\:mm")</span>@Html.Raw(message)</div>
        </div>
}
@if (model.OpeningTimes != null && model.OpeningTimes.Any())
{
    <div id="boxOffice-times">
        <div class="col-md-6">
            @foreach (var info in openingTimesList1)
            {
                @BoxofficeTimeRow(info)
            }
        </div>
        <div class="col-md-6">
            @foreach (var info in openingTimesList2)
            {
                @BoxofficeTimeRow(info)
            }
        </div>
    </div>

}
else
{
    <div id="boxOffice-no-dates">We do not have anyone scheduled to man the box office at the moment. Keep checking back to find out when we will be opening the floodgates.</div>
}

@*<h2><span class="section-title">Current Shows</span></h2>
    @if (model.FunctionsAvailable != null && model.FunctionsAvailable.Any())
    {
        <ul>
            @foreach (var function in model.FunctionsAvailable)
            {
                <li>@function.DisplayName : @function.TicketsAvailableOnline : @function.TicketsAvailableOnlineFrom : @function.TicketsAvailableFromTheBoxOfficeInPerson : @function.TicketsAvailableFromTheBoxOfficeFrom</li>
            }
        </ul>
    }
    else
    {
        <div class="alert alert-danger">The box office doesn't currently have any opening times</div>
    }*@

Wells Operatic Society/Views/MacroPartials/LoginStatus.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@using System.Web.Mvc.Html
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginStatusModel = Members.GetCurrentLoginStatus();

    var logoutModel = new PostRedirectModel();

    logoutModel.RedirectUrl = "/"; 

}

@if (loginStatusModel.IsLoggedIn)
{
    <p>You are currently logged in as @loginStatusModel.Name</p>

    @*using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
    {
         <fieldset>
             <legend>Logout</legend>
             <button>Logout</button>
         </fieldset>
    
        @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }*@
}

Wells Operatic Society/Views/MacroPartials/MembershipDisplayManuals.cshtml
@using WellsOperaticSociety.BusinessLogic
@using WellsOperaticSociety.Models.UmbracoModels
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var dm = new DataManager();

    var documents = dm.GetManuals();
}
@functions
{
    private string GetDocumentUrl(Document document)
    {
        if (document == null || !document.DocumentFile.Any())
            return string.Empty;
        return document.DocumentFile.First().Url;
    }
    private string GetDocumentExtension(Document document)
    {
        if (document == null || !document.DocumentFile.Any())
            return string.Empty;

        string extension = document.DocumentFile.First().GetProperty("umbracoExtension").Value.ToString();
        return extension;
    }
}

@if (documents.Any())
{
    foreach (var manual in documents)
    {
        <div class="row uploaded-document">
            <div class="col-xs-2"><div class="file-icon file-icon-xl hidden-xs" data-type="@GetDocumentExtension(manual)"></div><div class="file-icon file-icon-lg visible-xs" data-type="@GetDocumentExtension(manual)"></div></div>
            <div class="col-xs-10">
                <a href="@GetDocumentUrl(manual)">
                    <h2>@manual.Name</h2>
                    <p>@Html.Raw(manual.GetPropertyValue<string>("description"))</p>
                </a>
            </div>
        </div>
    }
}
else
{
    <div class="alert alert-info">There are no manuals available yet</div>
}

Wells Operatic Society/Views/MacroPartials/MembershipDisplayMinutes.cshtml
@using WellsOperaticSociety.BusinessLogic
@using WellsOperaticSociety.Models.UmbracoModels
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var dm = new DataManager();

    var documents = dm.GetMinuets();
}
@functions
{
    private string GetDocumentUrl(Document document)
    {
        if (document == null || !document.DocumentFile.Any())
            return string.Empty;
        return document.DocumentFile.First().Url;
    }
    private string GetDocumentExtension(Document document)
    {
        if (document == null || !document.DocumentFile.Any())
            return string.Empty;

        string extension = document.DocumentFile.First().GetProperty("umbracoExtension").Value.ToString();
        return extension;
    }
}
@if (documents.Any())
{
    foreach (var minutes in documents)
    {
        <div class="row uploaded-document">
            <div class="col-xs-2"><div class="file-icon file-icon-xl hidden-xs" data-type="@GetDocumentExtension(minutes)"></div><div class="file-icon file-icon-lg visible-xs" data-type="@GetDocumentExtension(minutes)"></div></div>
            <div class="col-xs-10">
                <a href="@GetDocumentUrl(minutes)">
                    <h2>@minutes.Name</h2>
                    <p>@Html.Raw(minutes.GetPropertyValue<string>("description"))</p>
                </a>
            </div>
        </div>
    }
}
else
{
    <div class="alert alert-info">There are no minutes recorded yet</div>
}

Wells Operatic Society/Views/MacroPartials/MembershipHistory.cshtml
@Html.Action("MembershipHistory","MembershipSurface")

Wells Operatic Society/Views/MacroPartials/MembershipManageCards.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@Html.Action("ManageCards", "MembershipSurface")

Wells Operatic Society/Views/MacroPartials/MembershipManageSubscription.cshtml
@Html.Action("ManageSubscription","MembershipSurface")

Wells Operatic Society/Views/MacroPartials/PictureCard.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    string linkedContent = Model.MacroParameters["link"] as string;
    var link = string.Empty;
    if (!linkedContent.IsNullOrEmpty())
    {
        link = Umbraco.TypedContent(int.Parse(linkedContent)).Url;
    }
    string linkedMedia = Model.MacroParameters["image"] as string;
    var imageUrl = string.Empty;
    if (!linkedMedia.IsNullOrEmpty())
    {
        imageUrl = Umbraco.TypedMedia(int.Parse(linkedMedia)).Url;
    }

    var footerText = Server.HtmlDecode(Model.MacroParameters["footerText"]as string);
    var contentText = Server.HtmlDecode(Model.MacroParameters["contentText"] as string);
}

<div class="card card-background">
    <a href="@link">
        <div class="image" style="background-image: url('@imageUrl'); background-position: center center; background-size: cover;">
            <img src="@imageUrl" style="display: none;"/>
            <div class="filter"></div>
        </div>
        <div class="content text-center">
            <br/>
            <h1 class="title">@Html.Raw(contentText)</h1>
        </div>
        <div class="footer">
            <h4>@Html.Raw(footerText)</h4>
        </div>
    </a>
</div>

Wells Operatic Society/Views/MacroPartials/ResetPassword.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var t = Request.QueryString["token"] ?? string.Empty;
}
@Html.Action("AuthenticateResetPassword", "MembershipSurface",new {token = t })

Wells Operatic Society/Views/MacroPartials/SubscriptionForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@Html.Action("SubscriptionForm","MembershipSurface")

Wells Operatic Society/Views/MacroPartials/WhatsOn.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@Html.Action("WhatsOn", "MainSurface", new { quantity = 10 })